<?php

$myProduct = $block->getProduct(25);

    echo $myProduct->getName() . ' - ' . $myProduct->getPrice() . '<br />';

    ?>

<!--<p style="color:white; text-align:center">Contacts</p>-->
<!--<p style="color:white; text-align:center">Phone: +380954222590 (Vodafone)</p></br>-->
<!--<p style="color:white; text-align:center">Phone: +380634222590 (Kyivstar)</p></br>-->
<!---->
<!--<p style="color:white; text-align:center">Address: Akademika Valtera, 14 (Kyivstar)</p>-->


    <ul style="color:white; text-align:center">
        <li>Contacts</li>
        <li>Phone: +380954222590</li>
        <li>Phone: +380634222590 (Kyivstar)</li></br>
        <li>Address: Akademika Valtera, 14</li>

    </ul>
