
<!--<h1>--><?php //echo $this->getHelloWorldTxt(); ?><!--</h1>-->
<!--<p>--><?php //echo $this->sayHello() ?><!--</p>-->



    <?php
    //    $categoryId = 3; // fetching products in category id 6
    //    $categoryProducts = $block->getCategoryProducts($categoryId);
    //    foreach ($categoryProducts as $product) {
    //        echo $product->getName() . ' - ' . $product->getProductUrl() . '<br />';
    //    }

        $myProducts = $block->getProductData();

        foreach ($myProducts as $product) {

            ?>
            <div style="overflow: hidden;display:inline-block;border:1px solid black">
            <?php

            echo $product->getName() . ' - ' . $product->getPrice() . '<br />';

                $productimages = $product->getMediaGalleryImages();
                foreach($productimages as $productimage)
                {
                   ?>
                    <div style="width:90px; height:180px; display:inline-block;border:1px solid black" >
                      <?php  echo "<img src = ".$productimage['url']. " height=100 width=100 />"; ?>
                    </div>
                     <?php
                }
            ?>
            </div>
        <?php
        }
    ?>
