<div style="margin-top:30%; text-align: center;">
    <a href=<?php echo $this->getScoupeConfigFB(); ?>><img src="<?php echo $this->getViewFileUrl('Vaimo_Helloworld::images/facebook.svg'); ?>"  width="30"
                                     height="30" alt="Пример"></a>
    <a href=<?php echo $this->getScoupeConfigInsta(); ?>><img src="<?php echo $this->getViewFileUrl('Vaimo_Helloworld::images/instagram.svg'); ?>" width="30"
                                    height="30" alt="Пример"></a>
    <a href=<?php echo $this->getScoupeConfigTelegram(); ?>><img src="<?php echo $this->getViewFileUrl('Vaimo_Helloworld::images/telegram.svg'); ?>" width="30"
                                              height="30" alt="Пример"></a>
</div>


